version: 2.1
description: Build Tabris.js apps

orbs:
  tabris:
    executors:
      android_executor:
        docker:
          - image: circleci/android:api-28-node
    jobs:
      build:
        parameters:
          platform:
            description: The platform to build. Either "android" or "ios".
            type: string
            default: android
          path:
            description: The path to the app inside the repository. Defaults to the root directory.
            type: string
            default: ./
        executor: android_executor
        steps:
          - checkout
          - run: sudo npm install tabris-cli -g
          - run: cd <<parameters.path>> && tabris build <<parameters.platform>>

workflows:
  "Tabris build":
    jobs:
      - tabris/build:
          platform: android
          path: .example
