version: 2.1
description: Build Tabris.js apps

orbs:
  tabris:
    executors:
      android_executor:
        docker:
          - image: circleci/android:api-28-node
    jobs:
      build:
        parameters:
          platform:
            description: The platform to build. Either "android" or "ios".
            type: enum
            enum: [android, ios]
            default: android
          path:
            description: The path to the app inside the repository. Defaults to the root directory.
            type: string
            default: ./
          tabris-cli-version:
            description: The version of the tabris-cli to use for the build
            type: string
            default: nightly
          gradle-version:
            description: The gradle version to make available to the build
            type: string
            default: 4.10.3
        executor: android_executor
        steps:
          - checkout
          - run: |
              sudo apt-get -q install gradle # required to let cordova use its own gradle wrapper
              sudo npm install tabris-cli@<<parameters.tabris-cli-version>> -g -q
              cd <<parameters.path>>
              npm install --save-dev
              tabris build <<parameters.platform>>
          - store_artifacts:
              path: $CIRCLE_WORKING_DIRECTORY/<<parameters.platform>>/build/cordova/platforms/android/app/build/outputs/apk
              destination: apk
workflows:
  "Tabris build":
    jobs:
      - tabris/build:
          platform: android
          path: .example
