version: 2.1
description: Build Tabris.js apps

orbs:
  tabris:
    executors:
      android_executor:
        docker:
          - image: circleci/android:api-28-node
    jobs:
      build:
        parameters:
          platform:
            description: The platform to build. Either "android" or "ios".
            type: enum
            enum: [android, ios]
            default: android
          path:
            description: The path to the app inside the repository. Defaults to the root directory.
            type: string
            default: ./
          tabris-cli-version:
            description: The version of the tabris-cli to use for the build
            type: string
            default: nightly
        executor: android_executor
        steps:
          - checkout
          - run: # Required to let cordova download its own gradle wrapper to run the build.
              name: Install gradle globally
              command: sudo apt-get -qq install gradle
          - run:
              name: Install tabris-cli@<<parameters.tabris-cli-version>> used to build the app
              command: sudo npm install tabris-cli@<<parameters.tabris-cli-version>> -g -q
          - run:
              name: Build tabris <<parameters.platform>> app
              working_directory: <<parameters.path>>
              command: |
                  npm install --save-dev
                  tabris build <<parameters.platform>>
          - store_artifacts:
              path: <<parameters.path>>/build/cordova/platforms/android/app/build/outputs/apk
              destination: apk
workflows:
  "Build lottie app":
    jobs:
      - tabris/build:
          platform: android
          path: .example
