version: 2.1
description: Build Tabris.js apps

orbs:
  tabris:
    executors:
      android_executor:
        docker:
          - image: circleci/android:api-28-node
    commands:
      printmessage:
        steps:
          - run: echo "We will now do special things"
      install_tabris_cli:
        steps:
          - run: sudo npm install tabris-cli -g
      cd_to_app_dir:
        parameters:
          path:
            type: string
        steps:
          - run: pwd
          - run: ls -la
          - run: cd <<parameters.path>>
          - run: ls -la
      tabris_build:
        parameters:
          platform:
            type: string
        steps:
          - run: tabris build <<parameters.platform>>
    jobs:
      build:
        parameters:
          platform:
            description: The platform to build. Either "android" or "ios".
            type: string
            default: android
          path:
            description: The path to the app inside the repository. Defaults to the root directory.
            type: string
            default: ./
        executor: android_executor
        steps:
          - printmessage
          - checkout
          - install_tabris_cli
          - cd_to_app_dir:
              path: <<parameters.path>>
          - tabris_build:
              platform: <<parameters.platform>>

workflows:
  "Tabris build":
    jobs:
      - tabris/build:
          platform: android
          path: .example
